export const SUBMISSION_STATUS = {
  DRAFT: "DRAFT",
  POSTED: "POSTED",
  APPROVED: "APPROVED",
  PUBLISHED: "PUBLISHED",
  REJECTED: "REJECTED",
};

export const SUBMISSION_STATUS_COLOR = {
  DRAFT: "#FFD700",
  POSTED: "#FFA500",
  APPROVED: "#32CD32",
  PUBLISHED: "#4169E1",
  REJECTED: "#DC143C",
};

export const SUBMISSION_STATUSES = Object.values(SUBMISSION_STATUS);
export const SUBMISSION_STATUS_COLORS = Object.values(SUBMISSION_STATUS_COLOR);
