export const COOKIE_MAX_AGE_1_YEAR = 365 * 24 * 60 * 60

export const SUBMISSION_STATUS = {
  DRAFT: "DRAFT",
  POSTED: "POSTED",
  APPROVED: "APPROVED",
  PUBLISHED: "PUBLISHED",
  REJECTED: "REJECTED",
}
  
export const SUBMISSION_STATUSES = Object.values(SUBMISSION_STATUS)
